apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ["sleep", "infinity"]
        resources: {}
  strategy:
    canary:                        # Changed from rollingUpdate or recreate
      steps:
      - setWeight: 20
      - pause: {}