apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: test-app-rollout
  name: test-app-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-rollout
  template:
    metadata:
      labels:
        app: test-app-rollout
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ["sleep", "infinity"]
        resources: {}
  strategy:
    canary:                        
      steps:
      - setWeight: 20
      - pause: {}